###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:9.6-alpine
      container_name: codebb-pl-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=dev
        - POSTGRES_PASSWORD=dev
        - POSTGRES_DB=dev

    webserver:
      image: nginx:alpine
      container_name: codebb-pl-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "10900:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: codebb-pl-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

